### ISSUE TITLE
Effekt der SR Korrektur berechnen.

### ISSUE THREAD

**Issue by mic-haf** [e-sr/SDWirkungNi#3]
@e-sr 
Ich fände es "pädagogisch" wertvoll, wenn zumindest der Fall c) als Korrektur auf die Wirkung der SD-Typen angewendet würde. Denn das wäre doch eigentlich logisch. Die SR muss berücksichtigt werden. Sonst macht ja sonRail auch wenig Sinn.
Es wäre doch interessant zu sehen, was mit der Wirkung der SD nach konkret passieren würde. D.h. ja nicht, dass man dann dieser Wirkungsberechnung mehr vertraut. Aber auf jeden Fall relativiert sie die "andere" Wirkung (ohne SR Korrektur).
Wäre es aufwendig für dich, die Wirkung so zu korrigieren und in einer kleinen Tabelle im SR Dokument darzustellen?

**Comment by e-sr** [comment]
Es ist möglich, nächste Woche kann ich das ausprobieren für einen bestimmte Fall :
- Wagen bezogene  Spektren Typ Wagen. Fur andere Wagentypen ist  wahrscheinlich die RR zu hoch um die Korrektur zu akzeptieren

**Comment by e-sr** [comment]
@mic-haf 

Ich habe  dein Input berücksichtigt im letzten commit. Ist es in Ordnung?  Diskussionen und Wichtige Erkenntnisse sind leicht modifiziert. Vielleicht sollte noch mehr darauf aufmerksam gemacht werden dass SR Korrekturen auf kleinere Wirkung hindeuten

**Comment by mic-haf** [comment]
@e-sr 
ich hab es durchgelesen und überarbeitet. Finde es gut so.

**Comment by e-sr** [comment]
Ab  92d14d562365610b64a372271ddd2ab31fada532 Berücksichtigt und korrigiert.
