### ISSUE TITLE
SR 2cm und 2000 Hz Spitzen zufällig kongruent?

### ISSUE THREAD

**Issue by mic-haf** [e-sr/SDWirkungNi#4]
@e-sr 
Du schreibst, dass die 2000Hz Spitze die These stützt, dass die SR in der Wellenlänge 2cm gross ist. Gemessen wird diese Rauheit aber bei einigen Abschnitten durch MBBM nicht.
Hast du auch akustische Messungen von langsameren Fahrzeugen, welche eine Spitze im tieferen Frequenzbereich haben und auch zu dieser 2cm Wellenlänge passen würden?
Als Kontrolle wäre dies wertvoll. Denn was, wenn die 2000 Hz Spitze nur zufällig mit der 2cm Wellenlänge korreliert und eigentlich nicht die Ursache in der SR hat?
Denn: entweder taugt die SR-Messung nichts, oder das Anregungsmodell berücksichtigt etwas zentrales nicht. Aber was???

**Comment by e-sr** [comment]
Es gibt eine vorbeifahrt. die ich dort nicht angezeigt habe da zu langsam. Schaue die neue Version vom bericht. Es gibt eine neues Bild
